# Generated by Django 5.1.4 on 2024-12-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('size', models.CharField(max_length=50, verbose_name='Размер зала')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение зала')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
    ]
